# Site settings
title: aric.hagberg.org
email: aric.hagberg@gmail.com
url: https://aric.hagberg.org
description: "Aric Hagberg.  Mathematics, Algorithms, Software, Hardware"
baseurl: ''

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Aric Hagberg

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: https://github.com/hagberg
  - title: stack-overflow
    url: http://stackoverflow.com/users/497234/aric
  - title: linkedin
    url: https://www.linkedin.com/in/arichagberg


# Build settings
markdown: kramdown
permalink: pretty

#port: 4000
#auto: true
#safe: true
#server: true
#pygments: true

scholar:
  style: assets/ieee-with-url.csl
  locale: en

  sort_by: year
  order: descending
  group_by: year
  group_order: descending

  source: .
  bibliography: papers/aric-hagberg.bib
  bibliography_template: bib
  bibliography_list_tag: ul

  details_dir:    bibliography
  details_layout: bibtex.html
  details_link:   Details

  replace_strings: true

  repository: papers

  query: "@*"
