# Site settings
title: aric.hagberg.org
email: aric.hagberg@gmail.com
url: https://aric.hagberg.org
description: "Aric Hagberg.  Mathematics, Algorithms, Software"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Aric Hagberg

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: https://github.com/hagberg
  - title: stack-overflow
    url: http://stackoverflow.com/users/497234/aric
  - title: linkedin
    url: https://www.linkedin.com/in/arichagberg


# Build settings
markdown: kramdown
permalink: pretty

#port: 4000
#auto: true
#safe: true
#server: true
#pygments: true
